### PR TITLE
Introduce changelog

### PR DESCRIPTION
**Pull request by timvisher**
I think a well-maintained changelog is an incredibly valuable tool.
Hopefully this is an acceptable start?

### CODE REVIEW

**Comment by timvisher** [comment]
ping :)

**Comment by weavejester** [comment]
The API hasn't had any significant changes, so adding a changelog is low on my priorities.

**Comment by devn** [comment]
I'd second this, mainly because environ is central to how some of the applications I'm working on are configured. Even for small changes, I think there's value. I just ran `lein ancient` and saw there's a 1.0.2 release. Without having a changelog, it's slightly more painful to review if any of the changes are changes I need to know about before saying OK to bumping the version.

**Comment by weavejester** [comment]
I guess it would be useful to list the bugs that have been fixed, now that Environ has had a couple of patches. No new functionality has been added, though, since neither the minor nor major version have been incremented.

**Comment by timvisher** [comment]
@weavejester Thanks for getting something out there! FWIW, the format I included in this pr is really helpful because it links to the pr involved in the change item and includes links to the compare page for a release. It's heavier weight than what you have but I'd appreciate it. :)

**Comment by weavejester** [comment]
I don't really see the point of providing more than just a summary for the changelog. The commit log provides additional details if people want to know specific dates or authors (`git log 1.0.1..1.0.2`), or to compare the differences between two versions (`git diff 1.0.1 1.0.2`).  The changelog is just there for an overview. Adding additional details makes it less readable at a glance, IMO.

**Pull request closed without merging**
