### PR TITLE
Change all occurrences of postgres to postgresql in README

### PR DESCRIPTION
**Pull request by A-Helberg**
I am very new to the Java world, so please close if this is misguided.

I don't believe there is a jdbc driver for "postgres", but should instead be "postgresql"
I copied from the README and had a fun time trying to figure out what the resulting errors meant.

### CODE REVIEW

**Comment by weavejester** [comment]
That's a good catch. Can you capitalize the first letter of your commit message, and perhaps note that it's changing things in the README. So maybe:

    Fix PostgreSQL URLS in README

**Comment by A-Helberg** [comment]
Made a new PR:
https://github.com/weavejester/environ/pull/64

**Comment by weavejester** [comment]
When you need to make changes to a commit, you don't need to create a new pull request. Instead, just alter the commit (e.g. `git commit --amend`) and then force-push the branch (e.g. `git push -f`).

**Comment by A-Helberg** [comment]
Thanks a friend told me as well, I made the first commit directly on github, so when I cloned the repo, it didn't allow me to amend. Sorry about that! 😳

**Pull request closed without merging**
