### PR TITLE
Print warnings to STDERR to avoid polluting STDOUT

### PR DESCRIPTION
**Pull request by dmatysiak**
Printing warnings to STDOUT pollutes the output of any program that uses STDOUT. This patch makes sure warnings are directed to STDERR.

### CODE REVIEW

**Comment by Quezion** [comment]
@weavejester I'm running into an issue now where a `clj` invocation in my automation is returning a bogus value because of the STDOUT pollution due to key `:java-home`.

```
Warning: environ value /usr/local/openjdk-8/ for key :java-home has been overwritten with /usr/local/openjdk-17
```

Can this PR be merged into a new release? I'd like to uptake it so that I can introduce Environ into this app, but it's a hard sell to the team if I can't get it working without kludges.

**Comment by weavejester** [comment]
This PR fell between the cracks for me. I'd be fine with merging it, once the small typo in the commit message is fixed:

    Print warnings to STDERR to avoid polluting STDOUT

**Comment by pedrorgirardi** [comment]
Hi @weavejester . Any update on this PR?

I was also bitten by **environ** writing to **stdout** 😅

**Comment by weavejester** [comment]
> Hi @weavejester . Any update on this PR?

As I said in my previous comment, I'm happy to merge once the typo in the commit message is corrected. This PR also now has 60 commits for some reason, when it should have 1.

**Comment by pedrorgirardi** [comment]
Thanks for the super quick response @weavejester !

Yeah, I noticed all the commits; I don't know what happened.

I'm not the author of the PR, so maybe we can ping @dmatysiak ?

**Comment by dmatysiak** [comment]
See https://github.com/weavejester/environ/pull/97. Didn't want to fiddle with the mess I accidentally made with the commit history in this branch.

**Comment by pedrorgirardi** [comment]
> See #97. Didn't want to fiddle with the mess I accidentally made with the commit history in this branch.

Nice! :) Thanks 🙏

**Pull request closed without merging**
