### PR TITLE
Added support to use JNDI resources.

### PR DESCRIPTION
**Pull request by turtle-bazon**
Also, need to test boot support functionality. At that moment I don't know how to do it correctly.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR, but I don't think that JNDI is a good fit for Environ. JNDI is complex and supports remote lookups, whereas Environ is simple and only concerned about the local environment.

You've also changed `env` from an immutable map into a custom mutable type that masquerades as an immutable map. That's not a direction I want to go in.

**Comment by turtle-bazon** [comment]
I need in environments that can bo looked up from local environment or inside app servers via jndi. And local or not is not matters. Because need properties in dev and production.
env is not mutable type and read only itself.

**Comment by weavejester** [comment]
> I need in environments that can bo looked up from local environment or inside app servers via jndi.

You could write your own JNDI library, and then merge the `environ.core/env` map in. You don't need this functionality in Environ to solve your problem.

> And local or not is not matters.

It does matter. Environ is a library with a narrow purpose. JNDI may be local, or it may be remote. Because we cannot distinguish between the two, JNDI support is not within Environ's design goals.

> env is not mutable type and read only itself.

Your `EnvironMap` type uses `javax.naming.InitialContext`, which is mutable:

```clojure
user=> (.bind (javax.naming.InitialContext.) "xyz" "abc")
nil
user=> (get environ.core/env :xyz)
"abc"
user=> (.rebind (javax.naming.InitialContext.) "xyz" "def")
nil
user=> (get environ.core/env :xyz)
"def"
```

Your type also fails to support normal map operations:

```clojure
user=> (environ.core/env :xyz)

ClassCastException environ.core.EnvironMap cannot be cast to clojure.lang.IFn  user/eval1300 (form-init5122955944727891533.clj:1)
user=> (assoc environ.core/env :xyz "abc")

AbstractMethodError Method environ/core/EnvironMap.assoc(Ljava/lang/Object;Ljava/lang/Object;)Lclojure/lang/IPersistentMap; is abstract  environ.core.EnvironMap (core.clj:-1)
```

**Comment by turtle-bazon** [comment]
ctx is mutable, you right. But instead of `(environ.core/env :xyz)` may be you means `(:xyz environ.core/env)`? Assoc is not implemented because it is not needed I think.

**Comment by turtle-bazon** [comment]
Ok. I need should be something like boot-environ but for JNDI.

**Comment by turtle-bazon** [comment]
Ok. I'll try to see problem in another angle.

**Comment by weavejester** [comment]
In Clojure, maps can be used as functions. So `(:foo m)` and `(m :foo)` are equivalent.

As for your problem, you could write something like this:

```clojure
(def config
  {:database-url (or (env :database-url) (jndi/get :database-url))})
```

So you build a configuration map by pulling data from the environment, or from JNDI.

**Comment by turtle-bazon** [comment]
In fact, I need property that I can configure in project.clj for development time and properties that configured in JNDI in production time. Problem solved using :jvm-opts and little code in clojure. So I don't need environ functionality at all. Thanks.

**Pull request closed without merging**
