### PR TITLE
Add support for Node.js

### PR DESCRIPTION
**Pull request by r0man**
Hi @weavejester,

I would like to use environ on Nodejs as well. I have seen the discussion on PR #70 and hope I followed your suggestions you mentioned with this PR.

I bumbed Clojure to 1.8, because I think recent ClojureScript requires it.

Would you be interested in merging this PR?

Roman

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR, but it doesn't look like you're taking into account non-Node environments. Can you ensure that the Node.js specific code is used only in Node.js environments?

**Comment by r0man** [comment]
Hi @weavejester,

about which environments are we talking here? And in which environments would environ be useful? I have Node.js and the browser in mind.

In a Node.js environment `process.env` is the equivalent of `System/env` on the JVM, so I think we agree on what should happen there.

For the browser I'm not aware of a similar API, so I would argure there's no reason to require environ in a browser environment. 

If you still do it with this PR, I guess you would get a compile error. So, yes, I think this should be improved. 

So, is the goal here to just make sure environ compiles in environments that don't support something like `System/env` and ensure the `env` is empty, or do you have other ideas?

Thanks, r0man.

**Comment by arichiardi** [comment]
Sorry to barge in here but for the browser in ClojureScript usually you would use a macro that reads `System/env` java stuff. At least this is how I have always done it. However I thing `goog-define` is the recommended way to go usually

**Comment by r0man** [comment]
@arichiardi Yes, I think `goog-define` is still the best solutions for browsers, or passing in the config to your "main" fn as EDN/JSON. My intention here was not to use `System/env` during compile time. Sometimes those lines get blurry :)

So to summarize, which plans do we have in which environments?
- Node.js -> environ.core/env == process.env
- Broswer -> environ.core/env ==  empty map

Is that correct?

**Comment by weavejester** [comment]
> about which environments are we talking here? And in which environments would environ be useful? I have Node.js and the browser in mind.

I don't have any specific environment in mind, but if a user does happen to require `environ.core` in a non-Node environment, I'd prefer that an exception wasn't thrown. Environ should be safe to require in any JS environment supported by ClojureScript, regardless of whether or not there are environment variables to load.

Essentially that just means we need to do some checks to ensure that if the required modules or methods are missing, `env` is just an empty map.

**Comment by weavejester** [comment]
> So to summarize, which plans do we have in which environments?
>
> *    Node.js -> environ.core/env == process.env
> *    Broswer -> environ.core/env == empty map
> 
> Is that correct?

Yes, that's right. If the required modules or methods are missing, `env` should just be an empty map.

**Comment by r0man** [comment]
@weavejester Ok, I added some checks and added a Nashorn build target which tests for the empty map. I picked Nashorn, because I think it has the least dependencies, provided we can assume JDK 8 for the tests.

One remaining issue is that on Node.js the `.boot-env` file is not read at the moment. I'm not too familiar with boot, but from what I understand this file neeeds to be read from the classpath and not the local directory. Are we fine with just adding a note to the README for this edge case?

**Comment by r0man** [comment]
@weavejester Anything I can do, to move this forward?

**Comment by weavejester** [comment]
I've just gotten back off vacation and I'm working my way through the backlog of PRs and issues. This should get merged in soon.

**Comment by r0man** [comment]
Thx!

**Pull request merged**
