### PR TITLE
Fix PostgreSQL URLS in README

### PR DESCRIPTION
**Pull request by A-Helberg**

### CODE REVIEW

**Comment by A-Helberg** [comment]
Curios about the structure of the commit messages, is there some place I can read up on the conventions and the rationale?

**Comment by weavejester** [comment]
Yep: http://chris.beams.io/posts/git-commit/#seven-rules

**Comment by weavejester** [comment]
Ack, sorry, I made the same mistake in my post, but could you change `URLS` to `URLs`? So run:

    git commit --amend

To change the commit text, and then:

    git push -f origin fix-readme-postgres-references

To overwrite the branch.

**Comment by A-Helberg** [comment]
😄 Done

**Comment by weavejester** [comment]
Perfect, thanks!

**Pull request merged**
