### PR TITLE
Add support for Boot

### PR DESCRIPTION
**Pull request by danielsz**
Please do not hesitate to ask for changes if something doesn't please you.

Thank you.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR, however, there are a few things that need to be changed before I can think about merging.

First, the commit message shouldn't say "This PR", because a commit isn't a pull request. Instead, write in the imperative tense, e.g. "Add support for Boot".

Second, you'll need to remove all references to the `danielsz` namespace, which I assume are there because you've released this as a third-party extension first.

Third, I don't understand the inclusion of the "bootlaces" library. It doesn't appear to be necessary.

Fourth, please follow the indentation style of the other environ files, particularly regarding the namespace declaration. Avoid trailing whitespace as well.

**Comment by danielsz** [comment]
Sure. Please let me know if there's anything else.

**Comment by danielsz** [comment]
I had initially made provisions for the boot task to be deployed on its own (like the leiningen plugin). However, the boot task can be shipped as part of the environ library, which simplifies installation and usage.

**Comment by danielsz** [comment]
In Boot, the round-trip via the filesystem is not necessary. Since there is only one single JVM instance, we can update the map directly in the #’environ.core namespace. Credit goes to @flyingmachine.

**Comment by weavejester** [comment]
Sorry it's taken me a while to come back to this. I have a few more concerns.

First, the `environ.boot` namespace should be in a separate "boot-environ" project, to match the "lein-environ" project.

Second, the `info` message is necessary. We don't have forced verbosity like that in the equivalent Leiningen plugin.

Third, I don't think your code correctly cleans up after itself. My understanding of Boot is that tasks can be run more than once in a session, so I believe the `environ` task needs a post wrapper that cleans up after itself, and sets the environment map back to its original value.

**Comment by danielsz** [comment]
No problem, James. Thank you for considering this. 

1, I'll do a separate "boot-environ". Do you need it to have a `project.clj`file? a `build.boot`file? Or shall I leave this to you?
2, I think you mean *not* necessary. I'll remove the `info` message.
3, This is actually a very sharp observation. You are 100% right. `with-redefs` is probably a better fit. 

```clojure
(deftask environ
  [e env FOO=BAR {kw edn} "The environment map"]
  (fn [next-task]
    (fn [fileset]
      (with-redefs [environ/env (merge environ/env env)]
        (next-task fileset)))))
```

Better, right?

I'll wait for your confirmation on all the above, and I'll push a new commit. Do you need me to squash it?

**Comment by weavejester** [comment]
1. I guess a `project.clj` file would fit in with the other projects, and make deploying it a slight easier.
2. Yes, I meant *not* necessary :)
3. Yes, that should be better. While the task is being executed, the `env` var is redefined only for the duration.

**Comment by danielsz** [comment]
Not sure about the naming of the namespace. Currently set to `boot-environ.plugin`. Please let me know if you have a better idea.

**Comment by danielsz** [comment]
Would you approve a `boot.environ` namespace?

**Comment by weavejester** [comment]
Perhaps `environ.boot` instead?

**Comment by danielsz** [comment]
Yes! That sounds about right.

**Comment by arrdem** [comment]
Is there anything I can do to help push this forwards?

**Comment by weavejester** [comment]
It's just a matter of me finding time to review it.

* The extra whitespace lines at the end of environ.boot should be removed.
* As should the whitespace around `:as`.
* The project description of boot-environ needs to be fixed.
* The README should probably mention the environ-boot dependency as well
* The commits then need to be squashed

**Comment by danielsz** [comment]
OK, I think I've gone through everything, except for the squashing. I'll wait your final review before doing just that.

**Comment by danielsz** [comment]
May I squash?

**Comment by weavejester** [comment]
Go ahead. This looks okay, and I'll play around with it a little before releasing.

**Comment by danielsz** [comment]
Done. Thanks a lot!

**Pull request merged**
